image: fedora:rawhide
stages:
  - build

variables:
  DEPENDENCIES: libusb1-devel glib2-devel nss-devel pixman-devel systemd meson gtk-doc
                gcc gcc-c++ glibc-devel libX11-devel libXv-devel


before_script:
  - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck $DEPENDENCIES && rpm -Uvh --oldpackage https://kojipkgs.fedoraproject.org//packages/meson/0.46.1/2.fc29/noarch/meson-0.46.1-2.fc29.noarch.rpm


build:
  stage: build
  script:
    - meson . _build
    - ninja -C _build
    - ninja -C _build install

